story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.Page1, name='Page1'),
    path('Page2/', views.Page2, name='Page2'),
    path('Page3/', views.Page3, name='Page3'),
    path('Page4/', views.Page4, name='Page4'),
    path('Page5/', views.Page5, name='Page5'),
    path('Page6/', views.Page6, name='Page6'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/delete', views.schedule_delete, name='schedule_delete'),

]

story4/models.py
from django.db import models
from datetime import datetime, date

class Schedule(models.Model):
    
    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

    

story4/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

story4/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from .import forms

# Create your views here.
def Page1(request):
    return render(request, 'Page1.html')

def Page2(request):
    return render(request, 'Page2.html')

def Page3(request):
    return render(request, 'Page3.html')

def Page4(request):
    return render(request, 'Page4.html')

def Page5(request):
    return render(request, 'Page5.html')

def Page6(request):
    return render(request, 'Page6.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story4:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

story4/templates/Page1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's Home</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div id="header"></div>
    <div class="center">
        <img id="bunga" src="{% static 'images/bunga.png' %}">
        <p id="nama">Rania <br>Azzahra</p>
    </div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/Page2.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's About</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="split left">
        <div class="titleleft">
            <p>About</p>
        </div>
    </div>
              
    <div class="split right">
        <div class="centered">
            <img class="img-responsive" src="{% static 'images/foto.jpg' %}" alt="Foto Rania">
            <p id="about">Usually called Nana, I’m a 19 years old undergraduate student, 
                        majoring in Information System at University of Indonesia. 
                        I am a people-person who have an IT background with extensive 
                        experiences in public relations. I have a good interpersonal 
                        skills and strong willingness to learn, which makes me eager 
                        to be challenged in order to grow and further improve my skills.</p>
        </div>
    </div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/Page3.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's Experience</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="split left">
        <div class="centered">
            <p id="year">2019</p>
            <p class="position">Indonesia Stock Exchange <br>
                                Software Development Intern</p>
            <p class="explanation">Indonesia Stock Exchange is a stock exchange that 
                                handles securities transactions in Indonesia. I am 
                                making the User Requirements, a document that specifies 
                                what the user expects the software to be able to do, 
                                and also maintaining SMARTS' server development.</p>
            <p id="year">2019</p>
            <p class="position">COMPFEST 11 <br>
                                Staff of Direct Marketing </p>
            <p class="explanation">COMPFEST is the biggest IT event held by students. 
                                    I am promoting the event by visiting high schools, 
                                    universities, and organizations, and being the master 
                                    of ceremony of COMPFEST's events, such as Academy, 
                                    Seminar, and Competition</p>
            <p id="year">2019</p>
            <p class="position">BEM Fasilkom UI <br> 
                                Staff of Human Resources Development Bureau</p>
            <p class="explanation">BEM Fasilkom UI is an organization to serve and create 
                                    meaningful creations for the benefits of Fasilkom UI. 
                                    I am maintaining internal relations of the organization 
                                    and being the person in charge of Upgrading Week, an 
                                    event where each bureau invites a speaker for a short 
                                    course about a certain topic of their choosing.</p>
        </div>

    </div>
              
    <div class="split right">
        <div class="titleright">
            <p>Experience</p>
        </div>
    </div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/Page4.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's Skills</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="split left">
        <div class="titleleft">
            <p>Skills</p>
        </div>
    </div>
              
    <div class="split right">
        <div class="centered">
            <img id="rose" src="{% static 'images/rose.png' %}" alt="bayangan bunga">
            <p class="position2">Basic Programming</p>
            <p class="explanation2">Python, Java, SQL</p>
            <p class="position2">Public Speaking </p>
            <p class="explanation2">Giving Presentation, Being the Master of Ceremony</p>
            <p class="position2">Organizational </p>
            <p class="explanation2">Leadership, Communication, Teamwork</p>
            <p class="position2">English </p>
            <p class="explanation2">Limited Working Proficiency</p>
            <p class="position2">Writing </p>
            <p class="explanation2">Making Paragraph, Article, etc.</p>
        </div>
    </div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/Page5.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's Contact</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div id="footer"></div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>

    <div class="split left">
        <div class="centered2">
            <a class="sosmed" href="mailto:nanaazzahra11@gmail.com">Email</a>
            <img class="sosmedimg" id="email" src="{% static 'images/email.png' %}">
            <a class="sosmed" href="tel:+6285921387321">Whatsapp</a>
            <img class="sosmedimg" id="wa" src="{% static 'images/whatsapp.png' %}">
        </div>
    </div>
                  
    <div class="split right2">
        <div class="centered2">
            <a class="sosmed" href="instagram.com/raniaaara">Instagram</a>
            <img class="sosmedimg" id="ig" src="{% static 'images/instagram.png' %}">
            <a class="sosmed" href="linkedin.com/in/rania-azzahra/">LinkedIn</a>
            <img class="sosmedimg" id="linked" src="{% static 'images/linkedin.png' %}">
        </div>
    </div>

    <div id="cr"><p>© 2019 Rania Azzahra. All Rights Reserved.</p></div>

</body>

story4/templates/Page6.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rania's Education</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="split left">
        <div class="centered">
            <img id="rose" src="{% static 'images/rose.png' %}" alt="bayangan bunga">
            <p class="position2">SDIT IQRO' Bekasi <br>
                                <i>2010-2012</i></p>
            <p class="position2">SMPIT Al-Kahfi Bogor<br>
                                <i>2012-2015</i></p>
            <p class="position2">SMAN 8 Jakarta <br> 
                                <i>2015-2018</i></p>
            <p class="position2">Sistem Informasi, Universitas Indonesia <br> 
                                <i>2018-Present</i></p>
        </div>

    </div>
              
    <div class="split right">
        <div class="titleright">
            <p>Education</p>
        </div>
    </div>

    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>
</body>

story4/templates/schedule.html
{% comment %} {% extends 'navbar.html' %} {% endcomment %}
<!DOCTYPE html>
{% load static %}
<html>


<head>
    <title>Rania's Schedule</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>
    
<body>
    <div class="navbar">
        <a href="{% url 'story4:Page1' %}"><p>Home</p></a>
        <a href="{% url 'story4:Page2' %}"><p>About</p></a>
        <a href="{% url 'story4:Page6' %}"><p>Education</p></a>
        <a href="{% url 'story4:Page4' %}"><p>Skills</p></a>
        <a href="{% url 'story4:Page3' %}"><p>Experience</p></a>
        <a href="{% url 'story4:Page5' %}"><p>Contact</p></a>
        <a href="{% url 'story4:schedule' %}"><p>Schedule</p></a>
    </div>

    <h1 class="rania">SCHEDULE</h1>
    
    <div class="article">
        <a href="{% url 'story4:schedule' %}"></a>
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <p id="activityName">{{ schedule.activity }}</p>
                        <p>{{ schedule.date.date }}</p>
                        <p>{{ schedule.time}}</p>
                        <p>{{ schedule.place }}</p>
                        <p>{{ schedule.category }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class = 'col-md-12'>
        <div class = 'form-group'>
            <div class='text-center'>
                <a href="{% url 'story4:schedule_delete' %}"><button type="button" class="btn btn-secondary btn-sm">Clear</button></a>
                <a href="{% url 'story4:schedule_create' %}"><button type="button" class="btn btn-secondary btn-sm">Create</button></a>
            </div>
        </div>
    </div>

</body>

story4/templates/schedule_create.html
{% comment %} {% extends 'navbar.html' %} {% endcomment %}
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Create Schedule</title>
    <link rel="shortcut icon" type="image" href="bunga-min.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story3.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div id="header"></div>

    <form class="create" action="{% url 'story4:schedule_create' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>

    
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-secondary" value="Add">
        </div>
        
    </form>

</body>